name: Sync Upstream Releases Only

on:
  schedule:
    - cron: '0 3 * * *'   # 每天凌晨3点自动执行
  workflow_dispatch:       # 支持手动手动触发

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List upstream releases
        run: |
          gh release list --repo ihmily/StreamCap --limit 100 > upstream.txt
          gh release list --limit 100 > my.txt

      - name: Find new releases
        id: find_new
        run: |
          comm -23 <(cut -f1 -d$'\t' upstream.txt | sort) <(cut -f1 -d$'\t' my.txt | sort) | grep -vE '^\s*$|^-$' > new_releases.txt
          echo "new_releases=$(paste -sd ',' new_releases.txt)" >> $GITHUB_OUTPUT
          echo "New releases to sync:"
          cat new_releases.txt || echo "(none)"

      - name: Sync new releases
        if: steps.find_new.outputs.new_releases != ''
        run: |
          for tag in $(cat new_releases.txt); do
            echo "Sync release $tag"
            release_json=$(gh release view "$tag" --repo ihmily/StreamCap --json name,body,isDraft,isPrerelease)
            name=$(echo "$release_json" | jq -r '.name')
            body=$(echo "$release_json" | jq -r '.body')
            draft=$(echo "$release_json" | jq -r '.isDraft')
            prerelease=$(echo "$release_json" | jq -r '.isPrerelease')

            mkdir -p downloads
            gh release download "$tag" --repo ihmily/StreamCap --dir downloads || echo "No assets"

            if [ "$(ls -A downloads)" ]; then
              gh release create "$tag" downloads/* --title "$name" --notes "$body" $( [ "$draft" == "true" ] && echo "--draft" ) $( [ "$prerelease" == "true" ] && echo "--prerelease" )
            else
              gh release create "$tag" --title "$name" --notes "$body" $( [ "$draft" == "true" ] && echo "--draft" ) $( [ "$prerelease" == "true" ] && echo "--prerelease" )
            fi

            rm -rf downloads
            echo "Release $tag synced"
          done

      - name: Finish
        run: echo "Releases sync complete"
