on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GH CLI
        uses: cli/cli-action@v2
      - name: Fetch upstream releases
        run: |
          gh release list --repo upstream-owner/upstream-repo > latest_upstream.txt
          gh release list --repo ${{ github.repository }} > latest_fork.txt
      - name: Compare and sync
        run: |
          for tag in $(grep -vFf latest_fork.txt latest_upstream.txt); do
            gh release download "$tag" --repo upstream-owner/upstream-repo
            gh release create "$tag" <*.zip> --repo ${{ github.repository }}
          done
